# Generated by Django 3.2.13 on 2022-06-13 17:36

from django.db import migrations, models
import nanoid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='id',
            field=models.CharField(default=nanoid.generate(size=32), editable=False, max_length=32, primary_key=True, serialize=False),
        ),
    ]
