# Generated by Django 3.2.13 on 2022-06-13 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id_product', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=255)),
                ('stock', models.IntegerField()),
                ('height', models.FloatField()),
                ('width', models.FloatField()),
                ('depth', models.FloatField()),
                ('cost', models.FloatField()),
                ('material', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usr_id', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('id_product',),
            },
        ),
    ]
