# Generated by Django 3.2.13 on 2022-06-10 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='pricePredictModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_score', models.FloatField()),
                ('qty', models.FloatField()),
                ('freight_price', models.FloatField()),
                ('product_weight_g', models.FloatField()),
                ('lag_price', models.FloatField()),
                ('comp_1', models.FloatField()),
                ('ps1', models.FloatField()),
                ('fp1', models.FloatField()),
                ('comp_2', models.FloatField()),
                ('ps2', models.FloatField()),
                ('fp2', models.FloatField()),
                ('bed_bath_table', models.FloatField()),
                ('computers_accessories', models.FloatField()),
                ('consoles_games', models.FloatField()),
                ('cool_stuff', models.FloatField()),
                ('furniture_decor', models.FloatField()),
                ('garden_tools', models.FloatField()),
                ('health_beauty', models.FloatField()),
                ('perfumery', models.FloatField()),
                ('watches_gifts', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usr_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
