# Generated by Django 3.2.13 on 2022-06-14 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import manager.generators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('price_predict', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockOut',
            fields=[
                ('stock_id', models.CharField(default=manager.generators.get_default_id, max_length=32, primary_key=True, serialize=False)),
                ('created_date', models.DateField(default=manager.generators.get_default_date)),
                ('removed_stock', models.PositiveIntegerField()),
                ('your_price', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='price_predict.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StockIn',
            fields=[
                ('stock_id', models.CharField(default=manager.generators.get_default_id, max_length=32, primary_key=True, serialize=False)),
                ('created_date', models.DateField(default=manager.generators.get_default_date)),
                ('added_stock', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='price_predict.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_date'],
                'abstract': False,
            },
        ),
    ]
